# Maven

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: a
  steps:
  - bash: echo hello world!!!
  - bash: ls -al
  - bash: ls -ltr
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
  - task: CmdLine@2
    inputs:
      script: |
        echo "I am custom script!";
        ls -ltr
  # Build your Java project and run tests with Apache Maven.
  # Add steps that analyze code, save build artifacts, deploy, and more:
  # https://docs.microsoft.com/azure/devops/pipelines/languages/java
  - task: CmdLine@2
    inputs:
      script: |
        echo "I am custom script!";
        ls -ltr
  # Build your Java project and run tests with Apache Maven.
  # Add steps that analyze code, save build artifacts, deploy, and more:
  # https://docs.microsoft.com/azure/devops/pipelines/languages/java
  - task: CmdLine@2
    inputs:
      script: |
        echo "I am custom script!";
        ls -ltr
  # Build your Java project and run tests with Apache Maven.
  # Add steps that analyze code, save build artifacts, deploy, and more:
  # https://docs.microsoft.com/azure/devops/pipelines/languages/java


  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

